"""lot_bids — заявки поставщиков с ценами

Revision ID: 2ac010466a64
Revises: cb03d00c8075
Create Date: 2026-07-27 15:32:10.948030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac010466a64'
down_revision: Union[str, Sequence[str], None] = 'cb03d00c8075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lot_bids',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_bin', sa.String(length=20), nullable=True),
    sa.Column('supplier_name', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('discount_price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('date_apply', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_bids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_bids_app_id'), ['app_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_bids_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_bids_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_bids_supplier_bin'), ['supplier_bin'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_bids_supplier_id'), ['supplier_id'], unique=False)

    # trgm-индексы (ix_lots_*_trgm, ix_organizations_name_trgm) заведены в БД
    # вручную и в models.py не описаны — autogenerate предлагал их снести,
    # блок удалён намеренно (как в cb03d00c8075).


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('lot_bids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_bids_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_lot_bids_supplier_bin'))
        batch_op.drop_index(batch_op.f('ix_lot_bids_status'))
        batch_op.drop_index(batch_op.f('ix_lot_bids_lot_id'))
        batch_op.drop_index(batch_op.f('ix_lot_bids_app_id'))

    op.drop_table('lot_bids')
    # ### end Alembic commands ###
