"""lots.enstru_code

Revision ID: 2d1439ed821b
Revises: efe63da702ee
Create Date: 2026-06-03 08:36:43.143428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d1439ed821b'
down_revision: Union[str, Sequence[str], None] = 'efe63da702ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enstru_code', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_lots_enstru_code'), ['enstru_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_enstru_code'))
        batch_op.drop_column('enstru_code')

    # ### end Alembic commands ###
