"""план закупок: таблица plan_points и lots.plan_root_id

Revision ID: 4b8146a060c7
Revises: c1a2b3d4e5f6
Create Date: 2026-08-06 09:30:38.181378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b8146a060c7'
down_revision: Union[str, Sequence[str], None] = 'c1a2b3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_points',
    sa.Column('root_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('point_id', sa.BigInteger(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('customer_bin', sa.String(length=20), nullable=True),
    sa.Column('customer_name', sa.String(length=500), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('extra_description', sa.Text(), nullable=True),
    sa.Column('enstru_code', sa.String(length=40), nullable=True),
    sa.Column('enstru_name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('trade_method_id', sa.Integer(), nullable=True),
    sa.Column('trade_method', sa.String(length=200), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=200), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('prepayment', sa.Float(), nullable=True),
    sa.Column('supply_date', sa.Text(), nullable=True),
    sa.Column('finsource', sa.String(length=300), nullable=True),
    sa.Column('budget_type', sa.String(length=300), nullable=True),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('kato', sa.String(length=20), nullable=True),
    sa.Column('place', sa.Text(), nullable=True),
    sa.Column('plan_act_number', sa.String(length=50), nullable=True),
    sa.Column('plan_act_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('versions', sa.Integer(), server_default='1', nullable=False),
    sa.Column('amount_initial', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('month_initial', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('root_id')
    )
    with op.batch_alter_table('plan_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_points_amount'), ['amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_customer_bin'), ['customer_bin'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_enstru_code'), ['enstru_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_kato'), ['kato'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_point_id'), ['point_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_status_id'), ['status_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_trade_method_id'), ['trade_method_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_points_year'), ['year'], unique=False)
        batch_op.create_index('ix_plan_points_year_category', ['year', 'category'], unique=False)
        batch_op.create_index('ix_plan_points_year_status', ['year', 'status_id', 'amount'], unique=False)

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_root_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lots_plan_root_id'), ['plan_root_id'], unique=False)

    # trgm-индексы в models.py не описаны (заведены вручную) — блок их
    # сноса из autogenerate удалён намеренно, как в a1d47569a180.


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_plan_root_id'))
        batch_op.drop_column('plan_root_id')

    with op.batch_alter_table('plan_points', schema=None) as batch_op:
        batch_op.drop_index('ix_plan_points_year_status')
        batch_op.drop_index('ix_plan_points_year_category')
        batch_op.drop_index(batch_op.f('ix_plan_points_year'))
        batch_op.drop_index(batch_op.f('ix_plan_points_trade_method_id'))
        batch_op.drop_index(batch_op.f('ix_plan_points_status_id'))
        batch_op.drop_index(batch_op.f('ix_plan_points_point_id'))
        batch_op.drop_index(batch_op.f('ix_plan_points_month'))
        batch_op.drop_index(batch_op.f('ix_plan_points_kato'))
        batch_op.drop_index(batch_op.f('ix_plan_points_enstru_code'))
        batch_op.drop_index(batch_op.f('ix_plan_points_customer_bin'))
        batch_op.drop_index(batch_op.f('ix_plan_points_created_at'))
        batch_op.drop_index(batch_op.f('ix_plan_points_category'))
        batch_op.drop_index(batch_op.f('ix_plan_points_amount'))

    op.drop_table('plan_points')
    # ### end Alembic commands ###
