"""announcement application_end

Revision ID: 64e32108f9eb
Revises: b5b7b314fff8
Create Date: 2026-06-03 07:31:31.915846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64e32108f9eb'
down_revision: Union[str, Sequence[str], None] = 'b5b7b314fff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_end', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_announcements_application_end'), ['application_end'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_application_end'))
        batch_op.drop_column('application_end')

    # ### end Alembic commands ###
