"""baseline schema

Revision ID: 792771485417
Revises: 
Create Date: 2026-05-20 06:29:08.651352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792771485417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_bin'), ['bin'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_name'), ['name'], unique=False)

    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kato', sa.String(length=20), nullable=True),
    sa.Column('amount_from', sa.Integer(), nullable=True),
    sa.Column('amount_to', sa.Integer(), nullable=True),
    sa.Column('status_codes', sa.JSON(), nullable=True),
    sa.Column('it_categories', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presets_active'), ['active'], unique=False)

    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('purchase_type', sa.String(length=100), nullable=True),
    sa.Column('subject_type', sa.String(length=50), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=True),
    sa.Column('organizer_address', sa.Text(), nullable=True),
    sa.Column('lots_count', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('attributes', sa.Text(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('contact_name', sa.String(length=300), nullable=True),
    sa.Column('contact_role', sa.String(length=200), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organizer_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_announcements_organizer_id'), ['organizer_id'], unique=False)

    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('preset_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('details_fetched', sa.Integer(), nullable=False),
    sa.Column('new_lots', sa.Integer(), nullable=False),
    sa.Column('updated_lots', sa.Integer(), nullable=False),
    sa.Column('new_documents', sa.Integer(), nullable=False),
    sa.Column('llm_analyzed', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=False),
    sa.Column('log_excerpt', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['preset_id'], ['presets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scrape_runs_preset_id'), ['preset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scrape_runs_started_at'), ['started_at'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('attribute', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=800), nullable=False),
    sa.Column('local_path', sa.String(length=800), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('download_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('announcement_id', 'url', name='uq_doc_url')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_announcement_id'), ['announcement_id'], unique=False)

    op.create_table('lots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('announcement_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('enstru', sa.String(length=500), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=100), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=True),
    sa.Column('amount_y1', sa.Float(), nullable=True),
    sa.Column('amount_y2', sa.Float(), nullable=True),
    sa.Column('amount_y3', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=200), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.Column('is_starred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('it_category', sa.String(length=50), nullable=True),
    sa.Column('kato', sa.String(length=20), nullable=True),
    sa.Column('method', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_announcement_id'), ['announcement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_enstru'), ['enstru'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_is_actual'), ['is_actual'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_is_starred'), ['is_starred'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_it_category'), ['it_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_kato'), ['kato'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_number'), ['number'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_plan_amount'), ['plan_amount'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_status_code'), ['status_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_lots_status_name'), ['status_name'], unique=False)

    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('plan_amount', sa.Float(), nullable=True),
    sa.Column('contract_amount', sa.Float(), nullable=True),
    sa.Column('fact_amount', sa.Float(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_status', sa.String(length=100), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contracts_contract_number'), ['contract_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contracts_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('lot_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('dev_category', sa.String(length=40), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('tz_summary', sa.Text(), nullable=True),
    sa.Column('solo_feasible', sa.Boolean(), nullable=True),
    sa.Column('vendor_lock_risk', sa.String(length=10), nullable=True),
    sa.Column('analysis_confidence', sa.String(length=10), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('analyzer_version', sa.String(length=40), nullable=False),
    sa.Column('tz_sha256', sa.String(length=64), nullable=True),
    sa.Column('source_document_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', name='uq_analysis_lot')
    )
    with op.batch_alter_table('lot_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_analyses_analysis_confidence'), ['analysis_confidence'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_analyses_dev_category'), ['dev_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_analyses_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_analyses_source_document_id'), ['source_document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_analyses_vendor_lock_risk'), ['vendor_lock_risk'], unique=False)

    op.create_table('lot_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=200), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_status_history_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lot_status_history_observed_at'), ['observed_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_status_history_observed_at'))
        batch_op.drop_index(batch_op.f('ix_lot_status_history_lot_id'))

    op.drop_table('lot_status_history')
    with op.batch_alter_table('lot_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_analyses_vendor_lock_risk'))
        batch_op.drop_index(batch_op.f('ix_lot_analyses_source_document_id'))
        batch_op.drop_index(batch_op.f('ix_lot_analyses_lot_id'))
        batch_op.drop_index(batch_op.f('ix_lot_analyses_dev_category'))
        batch_op.drop_index(batch_op.f('ix_lot_analyses_analysis_confidence'))

    op.drop_table('lot_analyses')
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contracts_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_lot_id'))
        batch_op.drop_index(batch_op.f('ix_contracts_contract_number'))

    op.drop_table('contracts')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_status_name'))
        batch_op.drop_index(batch_op.f('ix_lots_status_code'))
        batch_op.drop_index(batch_op.f('ix_lots_plan_amount'))
        batch_op.drop_index(batch_op.f('ix_lots_number'))
        batch_op.drop_index(batch_op.f('ix_lots_kato'))
        batch_op.drop_index(batch_op.f('ix_lots_it_category'))
        batch_op.drop_index(batch_op.f('ix_lots_is_starred'))
        batch_op.drop_index(batch_op.f('ix_lots_is_actual'))
        batch_op.drop_index(batch_op.f('ix_lots_first_seen'))
        batch_op.drop_index(batch_op.f('ix_lots_enstru'))
        batch_op.drop_index(batch_op.f('ix_lots_customer_id'))
        batch_op.drop_index(batch_op.f('ix_lots_announcement_id'))

    op.drop_table('lots')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_announcement_id'))

    op.drop_table('documents')
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_scrape_runs_preset_id'))

    op.drop_table('scrape_runs')
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_announcements_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_announcements_number'))

    op.drop_table('announcements')
    with op.batch_alter_table('presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presets_active'))

    op.drop_table('presets')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_name'))
        batch_op.drop_index(batch_op.f('ix_organizations_bin'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
