"""simhash dedup: documents.text_simhash + lot_analyses.reused_from_lot_id

Revision ID: b5b7b314fff8
Revises: 873b8b38eca0
Create Date: 2026-05-20 14:44:23.833747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b7b314fff8'
down_revision: Union[str, Sequence[str], None] = '873b8b38eca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_simhash', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_text_simhash'), ['text_simhash'], unique=False)

    with op.batch_alter_table('lot_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reused_from_lot_id', sa.BigInteger(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lot_analyses_reused_from_lot_id'), ['reused_from_lot_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_lot_analyses_reused_from_lot_id_lots',
            'lots', ['reused_from_lot_id'], ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lot_analyses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lot_analyses_reused_from_lot_id_lots', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lot_analyses_reused_from_lot_id'))
        batch_op.drop_column('reused_from_lot_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_text_simhash'))
        batch_op.drop_column('text_simhash')

    # ### end Alembic commands ###
