"""уведомления по плану: plan_notifications и users.notify_plan

Revision ID: c9de022db666
Revises: 4b8146a060c7
Create Date: 2026-08-06 11:31:37.875399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9de022db666'
down_revision: Union[str, Sequence[str], None] = '4b8146a060c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_query_id', sa.Integer(), nullable=False),
    sa.Column('plan_root_id', sa.BigInteger(), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_root_id'], ['plan_points.root_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_query_id'], ['user_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_query_id', 'plan_root_id', name='uq_plan_notif')
    )
    with op.batch_alter_table('plan_notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_notifications_plan_root_id'), ['plan_root_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_notifications_user_query_id'), ['user_query_id'], unique=False)

    # trgm-индексы в models.py не описаны (заведены вручную) — блок их
    # сноса из autogenerate удалён намеренно, как в a1d47569a180.

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_plan', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_plan')

    with op.batch_alter_table('plan_notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_notifications_user_query_id'))
        batch_op.drop_index(batch_op.f('ix_plan_notifications_plan_root_id'))

    op.drop_table('plan_notifications')
    # ### end Alembic commands ###
