"""scrape_run last_progress_at heartbeat

Revision ID: efe63da702ee
Revises: 64e32108f9eb
Create Date: 2026-06-03 07:54:04.435150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe63da702ee'
down_revision: Union[str, Sequence[str], None] = '64e32108f9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_progress_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_scrape_runs_last_progress_at'), ['last_progress_at'], unique=False)

    # ### end Alembic commands ###

    # Бэкофилл: у старых прогонов heartbeat'а не было. Берём момент последней
    # активности = finished_at (если закрыт) либо started_at. Зависшие прогоны
    # (finished_at NULL, стартовали давно) получат старый started_at и тут же
    # закроются reaper'ом (close_stale_runs) — ровно этого и хотим.
    op.execute(
        "UPDATE scrape_runs "
        "SET last_progress_at = COALESCE(finished_at, started_at) "
        "WHERE last_progress_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scrape_runs_last_progress_at'))
        batch_op.drop_column('last_progress_at')

    # ### end Alembic commands ###
